# Generated by Django 4.2.4 on 2023-08-15 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_create_by_post_updated_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='create_by',
            new_name='created_by',
        ),
    ]
